### PR TITLE
makerancidconf overhaul

### PR DESCRIPTION
**Pull request by inphobia**
most of the work done by @earendilfr in #408 & #417 , but somehow has gotten lost in the noise.

extra changes:
 * use strict & warnings
 * allow "-" in device types
 * rename variables/settings so they are more in line with what rancid uses.
 * reword the the documentation where needed
 * expand docs with a few common use cases

### CODE REVIEW

**Comment by inphobia** [comment]
would like to leave it here for a few days so @earendilfr has a chance to check it out, since he did most of the work.

**Comment by earendilfr** [comment]
Hi,

I will try to check it in few days (away from any computers currently).

Regards

**Comment by inphobia** [comment]
cool, take your time, no rush.

**Comment by inphobia** [comment]
i'll be most likely merging this somewhere early next week. should you not have time to check it out, no problem, you can always send us more improvements or suggestions later on.

**Comment by inphobia** [comment]
most work done by  @earendilfr

**Comment by inphobia** [comment]
also checked with heasley, the main rancid dev.  when i explained what we did & how it worked his reply was: "i think its cool; do as you wish."

**Pull request merged**
