### PR TITLE
SSH macsuck reimplementation of #1190

### PR DESCRIPTION
**Pull request by ollyg**

### CODE REVIEW

**Comment by ollyg** [comment]
Hi @earendilfr are you able to test the code in this branch, please?

**Comment by ollyg** [comment]
Hi @earendilfr are you able to test the code in this branch, please?

**Comment by earendilfr** [comment]
> Hi @earendilfr are you able to test the code in this branch, please?

Hello,
Pushed today in my test environment. I will let play it for next few days

**Comment by ollyg** [comment]
@earendilfr many thanks!

**Pull request merged**
